name: Nightmare Bot

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 30 minutes

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Make commit
        run: |
          echo "$(date)" >> server/nightmare.txt
          git config --global user.name 'Nightmare Bot'
          git config --global user.email 'mralabiemmanuel@gmail.com'
          git add .
          git commit -m "nightmare commit"
          git push
